### ISSUE TITLE
ESP32 da Heltec

### ISSUE THREAD

**Issue by carromeu** [EdanPotter/end-device-radioenge#1]
Olá! Por acaso funciona com a placa WiFi LoRa ESP32 (433MHz / 868MHz / 915MHz) da Heltec?

**Comment by afpastorio** [comment]
Olá. Acredito que funcione mas, só se você for utilizar o módulo da Radioenge, pois é pra ele que esta biblioteca foi feita. Segue link do módulo: https://www.radioenge.com.br/solucoes/iot/17-modulo-lorawan.html
